/* Boink FFI header — generated by cbindgen.
   This header declares the stable C ABI for the Boink engine.
   It contains only types and function signatures — the implementation
   lives in the native engine (C/C++). */

   // clang-format off

#if !defined(BOINK_API)
#if defined(_WIN32) || defined(__CYGWIN__)
#if defined(BOINK_BUILD_DLL)
#define BOINK_API __declspec(dllexport)
#elif defined(BOINK_USE_DLL)
#define BOINK_API __declspec(dllimport)
#else
#define BOINK_API
#endif
#else
#define BOINK_API __attribute__((visibility("default")))
#endif
#endif


#ifndef BOINK_C_API_H
#define BOINK_C_API_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define BOINK_C_API_VERSION_MAJOR 0

#define BOINK_C_API_VERSION_MINOR 2

#define BOINK_C_API_VERSION_PATCH 0

/**
 * Indicates successful operation.
 */
#define BOINK_OK 0

 /**
  * Indicates an invalid argument (for example a null pointer or an out-of-range value).
  */
#define BOINK_ERR_INVALID_ARG 1

  /**
   * Indicates that the output buffer was too small.
   */
#define BOINK_ERR_BUFFER_TOO_SMALL 2

   /**
    * Indicates that a requested object or identifier was not found.
    */
#define BOINK_ERR_NOT_FOUND 3
#define BOINK_ERR_UNSUPPORTED_FORMAT 4
#define BOINK_ERR_IO 5

    /**
     * Indicates an internal engine error.
     */
#define BOINK_ERR_INTERNAL 100

     /**
      * Represents an opaque engine handle.
      *
      * The pointer refers to an internal world or engine instance allocated
      * and owned by the native C or C++ side.
      */
typedef void* BoinkHandle;
typedef double Real;

/**
 * Represents a 3D vector in world coordinates (meters).
 */
typedef struct BoinkVec3 {
  /**
   * X component in meters.
   */
  Real x;
  /**
   * Y component in meters.
   */
  Real y;
  /**
   * Z component in meters.
   */
  Real z;
} BoinkVec3;

typedef unsigned char* BoinkVehicleMeshHandle;

/**
 * Describes the geometric and steering properties of a vehicle model.
 *
 * The vehicle model is shared by all vehicle entities in the world.
 */
typedef struct BoinkVehicleModel {
  BoinkVehicleMeshHandle mesh;
  BoinkVec3 center_of_mass;
  Real wheel_radius;
  Real suspension_rest_length;
  Real mass;
  /**
   * Maximum steering angle of the front wheels in degrees.
   */
  Real max_steer_angle;
} BoinkVehicleModel;

/**
 * Represents normalized control inputs of a driver.
 */
typedef struct BoinkControls {
  /**
   * Throttle demand in the range [0.0, 1.0].
   */
  Real throttle;
  /**
   * Brake demand in the range [0.0, 1.0].
   */
  Real brake;
  /**
   * Normalized steering input in the range [-1.0, 1.0].
   *
   * Negative values correspond to steering left.
   * Positive values correspond to steering right.
   */
  Real steer;
} BoinkControls;

/**
 * Represents a quaternion rotation (x, y, z, w).
 */
typedef struct BoinkQuaternion {
  Real x;
  Real y;
  Real z;
  Real w;
} BoinkQuaternion;

/**
 * Represents the full state of a vehicle at a specific simulation instant.
 */
typedef struct BoinkVehicleState {
  /**
   * Unique vehicle identifier.
   */
  uint64_t vehicle_id;
  /**
   * World position of the vehicle's chassis in meters.
   */
  struct BoinkVec3 chassis_position;
  /**
   * Orientation of the vehicle's chassis as a quaternion (x, y, z, w).
   */
  struct BoinkQuaternion chassis_orientation;
  /**
   * Linear speed magnitude of the vehicle in meters per second.
   */
  Real speed;
  /**
   * Engine speed in revolutions per minute.
   */
  Real engine_rpm;
  /**
   * Current gear value.
   *
   * - -1 – reverse
   * -  0 – neutral
   * -  1..8 – forward gears
   */
  int gear;
  /**
   * Effective throttle actually applied by the physics engine in the range [0.0, 1.0].
   */
  Real throttle_applied;
  /**
   * Effective brake actually applied by the physics engine in the range [0.0, 1.0].
   */
  Real brake_applied;
  BoinkVec3 wheel_position[4];
  BoinkQuaternion wheel_orientation[4];
  /**
   * Wheel angular speeds in revolutions per minute.
   *
   * Index mapping:
   *   [0] = front-left
   *   [1] = front-right
   *   [2] = rear-left
   *   [3] = rear-right
   */
  Real wheel_speeds[4];
} BoinkVehicleState;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

  /**
   * Retrieves the version of the Boink C API.
   *
   * Parameters:
   * - `out_major` – pointer to receive the major version number.
   * - `out_minor` – pointer to receive the minor version number.
   * - `out_patch` – pointer to receive the patch version number.
   *
   * Returns:
   * - `BOINK_OK` on success.
   * - An error code on failure.
   */
  BOINK_API int boink_get_c_api_version(unsigned int* out_major,
    unsigned int* out_minor,
    unsigned int* out_patch);

  /**
   * Retrieves the version of the Boink engine library.
   *
   * Parameters:
   * - `out_major` – pointer to receive the major version number.
   * - `out_minor` – pointer to receive the minor version number.
   * - `out_patch` – pointer to receive the patch version number.
   *
   * Returns:
   * - `BOINK_OK` on success.
   * - An error code on failure.
   */
  BOINK_API int boink_get_engine_version(unsigned int* out_major,
    unsigned int* out_minor,
    unsigned int* out_patch);

  /**
   * Initializes the Boink engine library.
   *
   * This function must be called before any other Boink API is used.
   *
   * Returns:
   * - `BOINK_OK` on success.
   * - An error code on failure.
   */
  BOINK_API int boink_init(bool debug_drawer_enable);
  BOINK_API void boink_terminate(void);

  BOINK_API BoinkHandle boink_create_race(const char* track_glb_filename);

  BOINK_API int boink_create_vehicle_mesh(
      const char* glb_model_filename,
      BoinkVehicleMeshHandle* out_mesh_handle);
  
  BOINK_API void boink_destroy_vehicle_mesh(BoinkVehicleMeshHandle handle);

  /**
   * Advances the simulation by a fixed time step.
   *
   * Parameters:
   * - `h` – handle to a valid world.
   * - `dt_seconds` – time step in seconds.
   *
   * Returns:
   * - `BOINK_OK` on success.
   * - An error code on failure.
   */
  BOINK_API int boink_step_race(BoinkHandle h, Real dt_seconds);
  BOINK_API int boink_get_simulation_duration(BoinkHandle h, Real* out_dur);
  BOINK_API void boink_update_debug();
  BOINK_API Real boink_get_time_debug();
  BOINK_API bool boink_should_close_debug();

  /**
   * Destroys a world instance created by `boink_create_world`.
   *
   * It is not required to despawn all vehicles before destroying the world.
   *
   * Parameters:
   * - `h` – handle to the world to destroy. Passing null is allowed and has
   *   no effect.
   */
  BOINK_API void boink_destroy_race(BoinkHandle h);

  /**
   * Spawns a new vehicle with a newly generated unique identifier.
   *
   * The engine owns the vehicle and manages its lifetime until it is despawned
   * or the world is destroyed.
   *
   * Parameters:
   * - `h` – handle to a valid world.
   * - `out_vehicle_id` – non-null pointer that receives the new vehicle identifier.
   *
   * Returns:
   * - `BOINK_OK` on success and writes the identifier to `*out_vehicle_id`.
   * - An error code if the engine cannot allocate or generate the identifier
   *   or if the arguments are invalid.
   */
  BOINK_API int boink_spawn_vehicle(BoinkHandle h, 
      const struct BoinkVehicleModel* vehicle_model,
      uint64_t* out_vehicle_id);

  /**
   * Removes a vehicle with the specified identifier.
   *
   * Parameters:
   * - `h` – handle to a valid world.
   * - `vehicle_id` – identifier of the vehicle to despawn.
   *
   * Returns:
   * - `BOINK_OK` on success.
   * - `BOINK_ERR_NOT_FOUND` if the vehicle does not exist.
   * - Another error code for other failures.
   */
  BOINK_API int boink_despawn_vehicle(BoinkHandle h, uint64_t vehicle_id);

  /**
   * Sets the desired driver controls for the specified vehicle.
   *
   * Parameters:
   * - `h` – handle to a valid world.
   * - `vehicle_id` – identifier of the vehicle to control.
   * - `controls` – non-null pointer to the desired control inputs.
   *
   * Returns:
   * - `BOINK_OK` on success.
   * - `BOINK_ERR_INVALID_ARG` if `controls` is null.
   * - `BOINK_ERR_NOT_FOUND` if the vehicle does not exist.
   * - Another error code for other failures.
   */
  BOINK_API int boink_set_controls(BoinkHandle h, uint64_t vehicle_id, const struct BoinkControls* controls);

  /**
   * Reads the current state of the specified vehicle.
   *
   * Parameters:
   * - `h` – handle to a valid world.
   * - `vehicle_id` – identifier of the vehicle whose state is requested.
   * - `out_state` – non-null pointer that receives the vehicle state.
   *
   * Returns:
   * - `BOINK_OK` on success and writes the state to `*out_state`.
   * - `BOINK_ERR_INVALID_ARG` if `out_state` is null.
   * - `BOINK_ERR_NOT_FOUND` if the vehicle does not exist.
   * - Another error code for other failures.
   */
  BOINK_API int boink_read_vehicle_state(BoinkHandle h, uint64_t vehicle_id, struct BoinkVehicleState* out_state);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* BOINK_C_API_H */

// clang-format on
