/* Boink FFI header — generated by cbindgen.
   This header declares the stable C ABI for the Boink engine.
   It contains only types and function signatures — the implementation
   lives in the native engine (C/C++). */

// clang-format off

#if !defined(BOINK_API)
  #if defined(_WIN32) || defined(__CYGWIN__)
    #if defined(BOINK_BUILD_DLL)
      #define BOINK_API __declspec(dllexport)
    #elif defined(BOINK_USE_DLL)
      #define BOINK_API __declspec(dllimport)
    #else
      #define BOINK_API
    #endif
  #else
    #define BOINK_API __attribute__((visibility("default")))
  #endif
#endif


#ifndef BOINK_C_API_H
#define BOINK_C_API_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define BOINK_C_API_VERSION_MAJOR 0

#define BOINK_C_API_VERSION_MINOR 6

#define BOINK_C_API_VERSION_PATCH 0

/**
 * Indicates successful operation.
 */
#define BOINK_OK 0

/**
 * Indicates an invalid argument (for example a null pointer or an out-of-range value).
 */
#define BOINK_ERR_INVALID_ARG 1

/**
 * Indicates that the output buffer was too small.
 */
#define BOINK_ERR_BUFFER_TOO_SMALL 2

/**
 * Indicates that a requested object or identifier was not found.
 */
#define BOINK_ERR_NOT_FOUND 3

/**
 * Indicates that the file format is not supported.
 */
#define BOINK_ERR_UNSUPPORTED_FORMAT 4

/**
 * Indicates an input/output error (for example a file read/write failure).
 */
#define BOINK_ERR_IO 5

/**
 * Indicates an internal engine error.
 */
#define BOINK_ERR_INTERNAL 100

/**
 * Represents an opaque engine handle.
 *
 * The pointer refers to an internal race or engine instance allocated
 * and owned by the native C or C++ side.
 */
typedef void *BoinkHandle;

/**
 * Represents an opaque handle to a vehicle mesh resource.
 */
typedef void *BoinkVehicleMeshHandle;

/**
 * Represents a real-valued numeric type.
 *
 * This type is used for floating-point values.
 * Should match the btScalar type.
 */
typedef float Real;

/**
 * Represents a 3D vector in world coordinates (meters).
 */
typedef struct BoinkVec3 {
  /**
   * X component in meters.
   */
  Real x;
  /**
   * Y component in meters.
   */
  Real y;
  /**
   * Z component in meters.
   */
  Real z;
} BoinkVec3;

/**
 * Represents one static centerline sample of a race track.
 *
 * Returned as part of `BoinkTrackData` by `boink_get_track_data`.
 */
typedef struct BoinkCenterlineSample {
  /**
   * Arc-length position along the lap in meters.
   */
  double s_m;
  /**
   * World-space centerline position.
   */
  struct BoinkVec3 position;
  /**
   * Track-forward unit vector.
   */
  struct BoinkVec3 tangent;
  /**
   * Track-local up unit vector.
   */
  struct BoinkVec3 normal;
  /**
   * Track-right unit vector.
   */
  struct BoinkVec3 right;
  /**
   * Drivable half-width to track-left from centerline, meters.
   */
  Real left_width_m;
  /**
   * Drivable half-width to track-right from centerline, meters.
   */
  Real right_width_m;
  /**
   * Signed centerline curvature [1/m].
   */
  Real curvature_1pm;
  /**
   * Longitudinal slope angle in radians.
   */
  Real grade_rad;
  /**
   * Crossfall/banking angle in radians around tangent.
   */
  Real bank_rad;
} BoinkCenterlineSample;

/**
 * Represents static track geometry for one lap.
 *
 * The `map_id` and `centerline_samples` pointers are owned by the engine
 * and must not be freed or modified by the caller.
 * These pointers remain valid until `boink_destroy_race(h)` is called.
 */
typedef struct BoinkTrackData {
  /**
   * Null-terminated UTF-8 track identifier.
   */
  const char *map_id;
  /**
   * Track geometry version.
   */
  unsigned int version;
  /**
   * Full lap length along centerline in meters.
   */
  double lap_length_m;
  /**
   * Number of elements at `centerline_samples`.
   */
  unsigned int centerline_sample_count;
  /**
   * Pointer to `centerline_sample_count` elements.
   *
   * Can be null only when `centerline_sample_count == 0`.
   */
  const struct BoinkCenterlineSample *centerline_samples;
} BoinkTrackData;

/**
 * Describes the geometric and steering properties of a vehicle model.
 *
 * The vehicle model is shared by all vehicle entities in the race.
 */
typedef struct BoinkVehicleModel {
  /**
   * Handle to the mesh of the vehicle.
   */
  BoinkVehicleMeshHandle mesh;
  /**
   * Position of the vehicle's center of mass in model space.
   */
  struct BoinkVec3 center_of_mass;
  /**
   * Radius of the vehicle wheels.
   */
  Real wheel_radius;
  /**
   * Rest length of the suspension.
   */
  Real suspension_rest_length;
  /**
   * Total mass of the vehicle.
   */
  Real mass;
  /**
   * Maximum steering angle of the front wheels in degrees.
   */
  Real max_steer_angle;
} BoinkVehicleModel;

/**
 * Represents normalized control inputs of a driver.
 */
typedef struct BoinkControls {
  /**
   * Throttle demand in the range [0.0, 1.0].
   */
  Real throttle;
  /**
   * Brake demand in the range [0.0, 1.0].
   */
  Real brake;
  /**
   * Normalized steering input in the range [-1.0, 1.0].
   *
   * Negative values correspond to steering left.
   * Positive values correspond to steering right.
   */
  Real steer;
} BoinkControls;

/**
 * Represents a quaternion rotation (x, y, z, w).
 */
typedef struct BoinkQuaternion {
  /**
   * X component of the vector part.
   */
  Real x;
  /**
   * Y component of the vector part.
   */
  Real y;
  /**
   * Z component of the vector part.
   */
  Real z;
  /**
   * W component (scalar part).
   */
  Real w;
} BoinkQuaternion;

/**
 * Represents the full state of a vehicle at a specific simulation instant.
 */
typedef struct BoinkVehicleState {
  /**
   * Unique vehicle identifier.
   */
  uint64_t vehicle_id;
  /**
   * World position of the vehicle's chassis in meters.
   */
  struct BoinkVec3 chassis_position;
  /**
   * Orientation of the vehicle as a quaternion (x, y, z, w).
   */
  struct BoinkQuaternion vehicle_orientation;
  /**
   * Linear speed magnitude of the vehicle in meters per second.
   */
  Real speed;
  /**
   * Engine speed in revolutions per minute.
   */
  Real engine_rpm;
  /**
   * Current gear value.
   *
   * - -1 - reverse
   * -  0 - neutral
   * -  1..8 - forward gears
   */
  int gear;
  /**
   * Effective throttle actually applied by the physics engine in the range [0.0, 1.0].
   */
  Real throttle_applied;
  /**
   * Effective brake actually applied by the physics engine in the range [0.0, 1.0].
   */
  Real brake_applied;
  /**
   * World-space positions of the vehicle wheels.
   *
   * Index mapping:
   *   [0] = front-left
   *   [1] = front-right
   *   [2] = rear-left
   *   [3] = rear-right
   */
  struct BoinkVec3 wheel_position[4];
  /**
   * Wheel angular speeds in radians per second.
   *
   * Index mapping:
   *   [0] = front-left
   *   [1] = front-right
   *   [2] = rear-left
   *   [3] = rear-right
   */
  Real wheel_speeds[4];
} BoinkVehicleState;

/**
 * Represents weather parameters applied globally to the race simulation.
 */
typedef struct BoinkWeather {
  /**
   * Cloudiness in range [0.0, 1.0].
   */
  Real cloudiness;
  /**
   * Ambient temperature in Celsius.
   */
  Real temperature_c;
  /**
   * Rain intensity in range [0.0, 1.0].
   */
  Real rain_intensity;
} BoinkWeather;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Retrieves the version of the Boink C API.
 *
 * Parameters:
 * - `out_major` - pointer to receive the major version number.
 * - `out_minor` - pointer to receive the minor version number.
 * - `out_patch` - pointer to receive the patch version number.
 *
 * Returns:
 * - `BOINK_OK` on success.
 * - An error code on failure.
 */
BOINK_API int boink_get_c_api_version(unsigned int *out_major,
                                   unsigned int *out_minor,
                                   unsigned int *out_patch);

/**
 * Retrieves the version of the Boink engine library.
 *
 * Parameters:
 * - `out_major` - pointer to receive the major version number.
 * - `out_minor` - pointer to receive the minor version number.
 * - `out_patch` - pointer to receive the patch version number.
 *
 * Returns:
 * - `BOINK_OK` on success.
 * - An error code on failure.
 */
BOINK_API int boink_get_engine_version(unsigned int *out_major,
                                    unsigned int *out_minor,
                                    unsigned int *out_patch);

/**
 * Retrieves the build profile string of the Boink engine library.
 *
 * Parameters:
 * - `out_buf` - destination buffer for a null-terminated string.
 * - `in_out_len` - in: buffer size in bytes; out: required size (incl. null).
 *
 * Returns:
 * - `BOINK_OK` on success.
 * - `BOINK_ERR_BUFFER_TOO_SMALL` if the buffer is too small.
 * - `BOINK_ERR_INVALID_ARG` on invalid pointers.
 */
BOINK_API int boink_get_engine_profile(char *out_buf, unsigned int *in_out_len);

/**
 * Retrieves a human-readable description of the last engine error.
 *
 * The error string is thread-local and is updated when a Boink API call fails.
 *
 * Parameters:
 * - `out_buf` - destination buffer for a null-terminated string.
 * - `in_out_len` - in: buffer size in bytes; out: required size (incl. null).
 *
 * Returns:
 * - `BOINK_OK` on success.
 * - `BOINK_ERR_BUFFER_TOO_SMALL` if the buffer is too small.
 * - `BOINK_ERR_INVALID_ARG` on invalid pointers.
 */
BOINK_API int boink_get_last_error(char *out_buf, unsigned int *in_out_len);

/**
 * Initializes the Boink engine library.
 *
 * This function must be called before any other Boink API is used.
 *
 * Parameters:
 * - `debug_drawer_enable`:
 *   Enables or disables the debug drawer used for visualizing.
 *
 * Returns:
 * - `BOINK_OK` on success.
 * - An error code on failure.
 */
BOINK_API int boink_init(bool debug_drawer_enable);

/**
 * Terminates the Boink engine library.
 *
 * This function releases all resources allocated by the library.
 * After calling this function, no other Boink API functions
 * may be used unless `boink_init` is called again.
 */
BOINK_API void boink_terminate(void);

/**
 * Creates a new race instance using the specified track file.
 *
 * The returned handle represents an internal race object managed by the engine.
 * The race must be destroyed with `boink_destroy_race` when no longer needed.
 *
 * Parameters:
 * - `track_glb_filename`:
 *   Path to the GLB file containing the track geometry and metadata.
 *
 * Returns:
 * - A valid `BoinkHandle` on success.
 * - Null on failure.
 */
BOINK_API BoinkHandle boink_create_race(const char *track_glb_filename);

/**
 * Destroys a race instance created by `boink_create_race`.
 *
 * It is not required to despawn all vehicles before destroying the race.
 *
 * Parameters:
 * - `h` - handle to the race to destroy. Passing null is allowed and has
 *   no effect.
 */
BOINK_API void boink_destroy_race(BoinkHandle h);

/**
 * Loads a vehicle mesh from a GLB model file.
 *
 * The created mesh can be shared by multiple vehicle instances and must
 * be destroyed with `boink_destroy_vehicle_mesh` when no longer needed.
 * The mesh handle must outlive all vehicles that reference it.
 *
 * Parameters:
 * - `glb_model_filename`:
 *   Path to the GLB file containing the vehicle mesh.
 * - `out_mesh_handle`:
 *   Pointer to receive the handle of the created mesh. Must not be null.
 *
 * Returns:
 * - `BOINK_OK` on success.
 * - An error code on failure.
 */
BOINK_API int boink_create_vehicle_mesh(const char *glb_model_filename,
                                     BoinkVehicleMeshHandle *out_mesh_handle);

/**
 * Destroys a vehicle mesh created by `boink_create_vehicle_mesh`.
 *
 * Passing a null handle has no effect. All vehicles using this mesh
 * must be destroyed before destroying the mesh.
 *
 * Parameters:
 * - `handle`:
 *   Handle of the vehicle mesh to destroy.
 */
BOINK_API void boink_destroy_vehicle_mesh(BoinkVehicleMeshHandle handle);

/**
 * Advances the race by a fixed time step.
 *
 * Parameters:
 * - `h` - handle to a valid race.
 * - `dt_seconds` - time step in seconds.
 *
 * Returns:
 * - `BOINK_OK` on success.
 * - An error code on failure.
 */
BOINK_API int boink_step_race(BoinkHandle h, Real dt_seconds);

/**
 * Retrieves the duration of the race.
 *
 * Parameters:
 * - h:
 *   Handle to a valid race.
 * - out_dur:
 *   Pointer to a `Real` variable that will receive the elapsed time
 *   in seconds. Must not be null.
 *
 * Returns:
 * - `BOINK_OK` on success.
 * - An error code on failure.
 */
BOINK_API int boink_get_race_duration(BoinkHandle h, Real *out_dur);

/**
 * Retrieves static track geometry for the specified race.
 *
 * The returned pointers inside `BoinkTrackData` are owned by the engine.
 *
 * Parameters:
 * - `h` - handle to a valid race.
 * - `out_track_data` - non-null output pointer.
 *
 * Returns:
 * - `BOINK_OK` on success.
 * - `BOINK_ERR_INVALID_ARG` if `out_track_data` is null.
 * - Another error code for other failures.
 */
BOINK_API int boink_get_track_data(BoinkHandle h, struct BoinkTrackData *out_track_data);

/**
 * Updates the debug drawer for the current frame.
 *
 * This function should be called once per frame if debug visualization
 * is enabled. It updates internal debug objects and draws them to the screen.
 *
 * Has no effect if the debug drawer is not enabled.
 */
BOINK_API void boink_update_debug(void);

/**
 * Retrieves the current debug time.
 *
 * Returns the elapsed time in seconds tracked by the debug drawer.
 * If the debug drawer is not enabled, this function returns 0.
 *
 * Returns:
 * - Elapsed time in seconds.
 */
BOINK_API Real boink_get_time_debug(void);

/**
 * Checks whether the debug visualization window should close.
 *
 * Returns true if either the debug drawer is not enabled or if the user
 * has requested the debug window to close.
 *
 * Returns:
 * - `true` if the debug window should close or debug is disabled.
 * - `false` if the debug window is open and should continue running.
 */
BOINK_API bool boink_should_close_debug(void);

/**
 * Spawns a new vehicle with a newly generated unique identifier.
 *
 * The engine owns the vehicle and manages its lifetime until it is despawned
 * or the race is destroyed.
 *
 * Parameters:
 * - `h` - handle to a valid race.
 * - `vehicle_model` - pointer to a `BoinkVehicleModel` that defines the
 *   properties of the vehicle.
 * - `out_vehicle_id` - non-null pointer that receives the new vehicle identifier.
 *
 * Returns:
 * - `BOINK_OK` on success and writes the identifier to `*out_vehicle_id`.
 * - An error code if the engine cannot allocate or generate the identifier
 *   or if the arguments are invalid.
 */
BOINK_API int boink_spawn_vehicle(BoinkHandle h,
                               const struct BoinkVehicleModel *vehicle_model,
                               uint64_t *out_vehicle_id);

/**
 * Removes a vehicle with the specified identifier.
 *
 * Parameters:
 * - `h` - handle to a valid race.
 * - `vehicle_id` - identifier of the vehicle to despawn.
 *
 * Returns:
 * - `BOINK_OK` on success.
 * - `BOINK_ERR_NOT_FOUND` if the vehicle does not exist.
 * - Another error code for other failures.
 */
BOINK_API int boink_despawn_vehicle(BoinkHandle h, uint64_t vehicle_id);

/**
 * Sets the desired driver controls for the specified vehicle.
 *
 * Parameters:
 * - `h` - handle to a valid race.
 * - `vehicle_id` - identifier of the vehicle to control.
 * - `controls` - non-null pointer to the desired control inputs.
 *
 * Returns:
 * - `BOINK_OK` on success.
 * - `BOINK_ERR_INVALID_ARG` if `controls` is null.
 * - `BOINK_ERR_NOT_FOUND` if the vehicle does not exist.
 * - Another error code for other failures.
 */
BOINK_API int boink_set_controls(BoinkHandle h,
                              uint64_t vehicle_id,
                              const struct BoinkControls *controls);

/**
 * Sets the world-space position of a vehicle.
 *
 * This immediately updates the specified vehicle's position in the simulation.
 *
 * Parameters:
 * - `h` - handle to a valid race.
 * - `vehicle_id` - identifier of the vehicle to move.
 * - `position` - non-null pointer to the new position vector.
 *
 * Returns:
 * - `BOINK_OK` on success.
 * - `BOINK_ERR_INVALID_ARG` if `position` is null.
 * - `BOINK_ERR_NOT_FOUND` if the vehicle does not exist.
 * - Another error code for other failures.
 */
BOINK_API int boink_set_vehicle_position(BoinkHandle h,
                                      uint64_t vehicle_id,
                                      const struct BoinkVec3 *position);

/**
 * Sets the world-space position on the track.
 *
 * This updates the track-relative position used for physics or race logic.
 *
 * Parameters:
 * - `h` - handle to a valid race.
 * - `position` - non-null pointer to the new track position vector.
 *
 * Returns:
 * - `BOINK_OK` on success.
 * - `BOINK_ERR_INVALID_ARG` if `position` is null.
 * - Another error code for other failures.
 */
BOINK_API int boink_set_track_position(BoinkHandle h, const struct BoinkVec3 *position);

/**
 * Reads the current state of the specified vehicle.
 *
 * Parameters:
 * - `h` - handle to a valid race.
 * - `vehicle_id` - identifier of the vehicle whose state is requested.
 * - `out_state` - non-null pointer that receives the vehicle state.
 *
 * Returns:
 * - `BOINK_OK` on success and writes the state to `*out_state`.
 * - `BOINK_ERR_INVALID_ARG` if `out_state` is null.
 * - `BOINK_ERR_NOT_FOUND` if the vehicle does not exist.
 * - Another error code for other failures.
 */
BOINK_API int boink_read_vehicle_state(BoinkHandle h,
                                    uint64_t vehicle_id,
                                    struct BoinkVehicleState *out_state);

/**
 * Sets global weather parameters used by the simulation engine.
 *
 * Parameters:
 * - `h` - handle to a valid race.
 * - `weather` - non-null pointer to weather parameters.
 *
 * Returns:
 * - `BOINK_OK` on success.
 * - `BOINK_ERR_INVALID_ARG` if `weather` is null.
 * - Another error code for other failures.
 */
BOINK_API int boink_set_weather(BoinkHandle h, const struct BoinkWeather *weather);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* BOINK_C_API_H */

// clang-format on
