/* Boink FFI header — generated by cbindgen.
   This header declares the stable C ABI for the Boink engine.
   It contains only types and function signatures — the implementation
   lives in the native engine (C/C++). */

#if !defined(BOINK_API)
  #if defined(_WIN32) || defined(__CYGWIN__)
    #if defined(BOINK_BUILD_DLL)
      #define BOINK_API __declspec(dllexport)
    #elif defined(BOINK_USE_DLL)
      #define BOINK_API __declspec(dllimport)
    #else
      #define BOINK_API
    #endif
  #else
    #define BOINK_API __attribute__((visibility("default")))
  #endif
#endif


#ifndef BOINK_H
#define BOINK_H

#pragma once

#include <stddef.h>
#include <stdint.h>

/**
 * Indicates successful operation.
 */
#define BOINK_OK 0

/**
 * Indicates an invalid argument (e.g. `NULL` pointer or out-of-range value).
 */
#define BOINK_ERR_INVALID_ARG 1

/**
 * Indicates that the output buffer was too small.
 */
#define BOINK_ERR_BUFFER_TOO_SMALL 2

/**
 * Indicates that a requested object or identifier was not found.
 */
#define BOINK_ERR_NOT_FOUND 3

/**
 * Indicates an internal engine error.
 */
#define BOINK_ERR_INTERNAL 100

/**
 * Represents an opaque engine handle.
 *
 * The pointer refers to an internal engine instance allocated
 * and owned by the native C++ side.
 */
typedef void *BoinkHandle;

/**
 * Represents normalized control inputs of a driver.
 */
typedef struct BoinkControls {
  /**
   * Throttle demand in range `[0.0, 1.0]`.
   */
  double throttle;
  /**
   * Brake demand in range `[0.0, 1.0]`.
   */
  double brake;
  /**
   * Normalized steering input in range `[-1.0, 1.0]`.
   *
   * Negative values correspond to steering left,
   * positive values correspond to steering right.
   */
  double steer;
} BoinkControls;

/**
 * Represents a 3D vector in world coordinates (meters).
 */
typedef struct BoinkVec3 {
  /**
   * X component in meters.
   */
  double x;
  /**
   * Y component in meters.
   */
  double y;
  /**
   * Z component in meters.
   */
  double z;
} BoinkVec3;

typedef struct BoinkCarModel{
  BoinkVec3 front_left_wheel;
  BoinkVec3 front_right_wheel;
  BoinkVec3 rear_left_wheel;
  BoinkVec3 rear_right_wheel;

  /**
   * Wheel max steer angle in degrees.
   */
  double max_steer_angle;
} BoinkCarModel;

/**
 * Represents roll–pitch–yaw orientation in radians.
 */
typedef struct BoinkEulerRPY {
  /**
   * Roll angle in radians.
   */
  double roll;
  /**
   * Pitch angle in radians.
   */
  double pitch;
  /**
   * Yaw angle in radians.
   */
  double yaw;
} BoinkEulerRPY;

/**
 * Represents the full state of a car at a specific simulation instant.
 */
typedef struct BoinkCarState {
  /**
   * Unique car identifier.
   */
  uint64_t car_id;
  /**
   * World position of the car in meters.
   */
  struct BoinkVec3 position;
  /**
   * Orientation of the car in roll–pitch–yaw angles (radians).
   */
  struct BoinkEulerRPY orientation;
  /**
   * Linear speed magnitude of the car in meters per second.
   */
  double speed;
  /**
   * Engine speed in revolutions per minute.
   */
  double engine_rpm;
  /**
   * Current gear value.
   *
   * - `-1` – reverse
   * - `0` – neutral
   * - `1..8` – forward gears
   */
  int gear;
  /**
   * Effective throttle actually applied by the physics engine `[0.0, 1.0]`.
   */
  double throttle_applied;
  /**
   * Effective brake actually applied by the physics engine `[0.0, 1.0]`.
   */
  double brake_applied;
  /**
   * Steering angles of the front wheels in radians.
   *
   * Order: `[0]` = front-left, `[1]` = front-right.
   */
  double wheel_angles[2];
  /**
   * Wheel angular speeds in revolutions per minute.
   *
   * Order: `[0]` = front-left, `[1]` = front-right,
   * `[2]` = rear-left, `[3]` = rear-right.
   */
  double wheel_speeds[4];
} BoinkCarState;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Returns the current ABI version as `MAJOR * 100 + MINOR`.
 */
BOINK_API int boink_abi_version(void);

/**
 * Initializes boink library.
 *
 * Returns BOINK_OK on success or an error code otherwise.
 */
BOINK_API int boink_init(void);

/**
 * Creates a new world instance.
 *
 * Returns a valid [`BoinkHandle`] on success, or `NULL` on failure.
 */
BOINK_API BoinkHandle boink_create_world(const struct BoinkCarModel* car_model);

/**
 * Starts simulation at given timepoint.
 *
 * The car model is the same for every car entity.
 *
 * Returns BOINK_OK on success or an error code otherwise.
 */
BOINK_API int boink_begin_world(
    BoinkHandle h, double timepoint);

/**
 * Destroys a world instance created by [`boink_create_world`].
 *
 * Passing `NULL` is allowed and has no effect.
 */
BOINK_API void boink_destroy_world(BoinkHandle h);

/**
 * Advances the simulation by a fixed time step (in seconds).
 *
 * Returns BOINK_OK on success or an error code otherwise.
 */
BOINK_API int boink_step(BoinkHandle h, double dt_seconds);

/**
 * Spawns a new car with new unique identifier.
 *
 * The cars are managed by library there is no need to call boink_despawn_call
 * before calling boink_destroy_world.
 *
 * Returns BOINK_OK on success or an error code if engine could not 
 * fetch the ID.
 */
BOINK_API int boink_spawn_car(BoinkHandle h, uint64_t* out_car_id);

/**
 * Removes a car with the specified identifier.
 *
 * Returns BOINK_OK on success or BOINK_ERR_NOT_FOUND if
 * the car does not exist.
 */
BOINK_API int boink_despawn_car(BoinkHandle h, uint64_t car_id);

/**
 * Retrieves the current number of active cars.
 *
 * The result is stored in the non-null pointer `out_count`.
 */
BOINK_API int boink_get_car_count(BoinkHandle h, size_t *out_count);

/**
 * Sets desired driver controls for the specified car.
 *
 * The pointer `controls` must not be null.
 */
BOINK_API int boink_set_controls(BoinkHandle h, uint64_t car_id, const struct BoinkControls *controls);

/**
 * Reads the current state of the specified car.
 *
 * The result is written to the non-null pointer `out_state`.
 */
BOINK_API int boink_read_car_state(BoinkHandle h, uint64_t car_id, struct BoinkCarState *out_state);

/**
 * Writes a snapshot of all cars into the provided buffer.
 *
 * - If `out_buf` is `NULL` or `out_cap` equals zero, no data is written
 *   and `*out_len` receives the total car count.
 * - If `out_cap` is smaller than the total number of cars, no data is written,
 *   `*out_len` receives the required count, and the function returns
 *   BOINK_ERR_BUFFER_TOO_SMALL.
 * - Otherwise, up to `out_cap` items are written to `out_buf`, and
 *   `*out_len` receives the number of items written.
 */
BOINK_API int boink_write_snapshot(BoinkHandle h,
                                struct BoinkCarState *out_buf,
                                size_t out_cap,
                                size_t *out_len);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* BOINK_H */
